package fr.formation.inti.entities;
// Generated 10 sept. 2019 09:21:11 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActiviteRecordHasSportifsId generated by hbm2java
 */
@Embeddable
public class ActiviteRecordHasSportifsId implements java.io.Serializable {

	private Date dateAjout;
	private int sportifsSportifsId;
	private int activiteRecordActiviteId;

	public ActiviteRecordHasSportifsId() {
	}

	public ActiviteRecordHasSportifsId(int sportifsSportifsId, int activiteRecordActiviteId) {
		this.sportifsSportifsId = sportifsSportifsId;
		this.activiteRecordActiviteId = activiteRecordActiviteId;
	}

	public ActiviteRecordHasSportifsId(Date dateAjout, int sportifsSportifsId, int activiteRecordActiviteId) {
		this.dateAjout = dateAjout;
		this.sportifsSportifsId = sportifsSportifsId;
		this.activiteRecordActiviteId = activiteRecordActiviteId;
	}

	@Column(name = "date_ajout", length = 10)
	public Date getDateAjout() {
		return this.dateAjout;
	}

	public void setDateAjout(Date dateAjout) {
		this.dateAjout = dateAjout;
	}

	@Column(name = "sportifs_sportifs_id", nullable = false)
	public int getSportifsSportifsId() {
		return this.sportifsSportifsId;
	}

	public void setSportifsSportifsId(int sportifsSportifsId) {
		this.sportifsSportifsId = sportifsSportifsId;
	}

	@Column(name = "activite_record_Activite_id", nullable = false)
	public int getActiviteRecordActiviteId() {
		return this.activiteRecordActiviteId;
	}

	public void setActiviteRecordActiviteId(int activiteRecordActiviteId) {
		this.activiteRecordActiviteId = activiteRecordActiviteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActiviteRecordHasSportifsId))
			return false;
		ActiviteRecordHasSportifsId castOther = (ActiviteRecordHasSportifsId) other;

		return ((this.getDateAjout() == castOther.getDateAjout()) || (this.getDateAjout() != null
				&& castOther.getDateAjout() != null && this.getDateAjout().equals(castOther.getDateAjout())))
				&& (this.getSportifsSportifsId() == castOther.getSportifsSportifsId())
				&& (this.getActiviteRecordActiviteId() == castOther.getActiviteRecordActiviteId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDateAjout() == null ? 0 : this.getDateAjout().hashCode());
		result = 37 * result + this.getSportifsSportifsId();
		result = 37 * result + this.getActiviteRecordActiviteId();
		return result;
	}

}
