package fr.formation.inti.entities;
// Generated 9 sept. 2019 11:09:20 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActiviteRecordHasSportifsId generated by hbm2java
 */
@Embeddable
public class ActiviteRecordHasSportifsId implements java.io.Serializable {

	private int activiteRecordActiviteId;
	private int sportifsSportifsId;

	public ActiviteRecordHasSportifsId() {
	}

	public ActiviteRecordHasSportifsId(int activiteRecordActiviteId, int sportifsSportifsId) {
		this.activiteRecordActiviteId = activiteRecordActiviteId;
		this.sportifsSportifsId = sportifsSportifsId;
	}

	@Column(name = "activite_record_Activite_id", nullable = false)
	public int getActiviteRecordActiviteId() {
		return this.activiteRecordActiviteId;
	}

	public void setActiviteRecordActiviteId(int activiteRecordActiviteId) {
		this.activiteRecordActiviteId = activiteRecordActiviteId;
	}

	@Column(name = "sportifs_sportifs_id", nullable = false)
	public int getSportifsSportifsId() {
		return this.sportifsSportifsId;
	}

	public void setSportifsSportifsId(int sportifsSportifsId) {
		this.sportifsSportifsId = sportifsSportifsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActiviteRecordHasSportifsId))
			return false;
		ActiviteRecordHasSportifsId castOther = (ActiviteRecordHasSportifsId) other;

		return (this.getActiviteRecordActiviteId() == castOther.getActiviteRecordActiviteId())
				&& (this.getSportifsSportifsId() == castOther.getSportifsSportifsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActiviteRecordActiviteId();
		result = 37 * result + this.getSportifsSportifsId();
		return result;
	}

}
