package fr.formation.inti.entities;
// Generated 9 sept. 2019 11:09:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActiviteRecordHasSportifs generated by hbm2java
 */
@Entity
@Table(name = "activite_record_has_sportifs", catalog = "sportnat")
public class ActiviteRecordHasSportifs implements java.io.Serializable {

	private ActiviteRecordHasSportifsId id;
	private Date dateAjout;

	public ActiviteRecordHasSportifs() {
	}

	public ActiviteRecordHasSportifs(ActiviteRecordHasSportifsId id) {
		this.id = id;
	}

	public ActiviteRecordHasSportifs(ActiviteRecordHasSportifsId id, Date dateAjout) {
		this.id = id;
		this.dateAjout = dateAjout;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "activiteRecordActiviteId", column = @Column(name = "activite_record_Activite_id", nullable = false)),
			@AttributeOverride(name = "sportifsSportifsId", column = @Column(name = "sportifs_sportifs_id", nullable = false)) })
	public ActiviteRecordHasSportifsId getId() {
		return this.id;
	}

	public void setId(ActiviteRecordHasSportifsId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ajout", length = 10)
	public Date getDateAjout() {
		return this.dateAjout;
	}

	public void setDateAjout(Date dateAjout) {
		this.dateAjout = dateAjout;
	}

}
