package fr.formation.inti.entities;
// Generated 5 sept. 2019 16:09:45 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActiviteRecord generated by hbm2java
 */
@Entity
@Table(name = "activite_record", catalog = "sportnat")
public class ActiviteRecord implements java.io.Serializable {

	private Integer activiteId;
	private Commentaire commentaire;
	private String nameActivity;
	private String lieu;
	private String timeofActivity;
	private Integer nbrePers;
	private Integer nbreKm;
	private String description;
	private Set<Sportifs> sportifses = new HashSet<Sportifs>(0);

	public ActiviteRecord() {
	}

	public ActiviteRecord(Commentaire commentaire) {
		this.commentaire = commentaire;
	}

	public ActiviteRecord(Commentaire commentaire, String nameActivity, String lieu, String timeofActivity,
			Integer nbrePers, Integer nbreKm, String description, Set<Sportifs> sportifses) {
		this.commentaire = commentaire;
		this.nameActivity = nameActivity;
		this.lieu = lieu;
		this.timeofActivity = timeofActivity;
		this.nbrePers = nbrePers;
		this.nbreKm = nbreKm;
		this.description = description;
		this.sportifses = sportifses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Activite_id", unique = true, nullable = false)
	public Integer getActiviteId() {
		return this.activiteId;
	}

	public void setActiviteId(Integer activiteId) {
		this.activiteId = activiteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commentaire_Commentaire_id", nullable = false)
	public Commentaire getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(Commentaire commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "NameActivity", length = 50)
	public String getNameActivity() {
		return this.nameActivity;
	}

	public void setNameActivity(String nameActivity) {
		this.nameActivity = nameActivity;
	}

	@Column(name = "Lieu", length = 50)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	@Column(name = "TimeofActivity", length = 50)
	public String getTimeofActivity() {
		return this.timeofActivity;
	}

	public void setTimeofActivity(String timeofActivity) {
		this.timeofActivity = timeofActivity;
	}

	@Column(name = "NbrePers")
	public Integer getNbrePers() {
		return this.nbrePers;
	}

	public void setNbrePers(Integer nbrePers) {
		this.nbrePers = nbrePers;
	}

	@Column(name = "NbreKm")
	public Integer getNbreKm() {
		return this.nbreKm;
	}

	public void setNbreKm(Integer nbreKm) {
		this.nbreKm = nbreKm;
	}

	@Column(name = "Description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "activite_record_has_sportifs", catalog = "sportnat", joinColumns = {
			@JoinColumn(name = "activite_record_Activite_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "sportifs_Login_id", nullable = false, updatable = false) })
	public Set<Sportifs> getSportifses() {
		return this.sportifses;
	}

	public void setSportifses(Set<Sportifs> sportifses) {
		this.sportifses = sportifses;
	}

}
