package fr.formation.inti.entities;
// Generated 5 sept. 2019 16:09:45 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name = "commentaire", catalog = "sportnat")
public class Commentaire implements java.io.Serializable {

	private int commentaireId;
	private Sportifs sportifs;
	private String expediteur;
	private String contenue;
	private Integer note;
	private Date dateRecord;
	private Set<ActiviteRecord> activiteRecords = new HashSet<ActiviteRecord>(0);

	public Commentaire() {
	}

	public Commentaire(int commentaireId, Sportifs sportifs) {
		this.commentaireId = commentaireId;
		this.sportifs = sportifs;
	}

	public Commentaire(int commentaireId, Sportifs sportifs, String expediteur, String contenue, Integer note,
			Date dateRecord, Set<ActiviteRecord> activiteRecords) {
		this.commentaireId = commentaireId;
		this.sportifs = sportifs;
		this.expediteur = expediteur;
		this.contenue = contenue;
		this.note = note;
		this.dateRecord = dateRecord;
		this.activiteRecords = activiteRecords;
	}

	@Id

	@Column(name = "Commentaire_id", unique = true, nullable = false)
	public int getCommentaireId() {
		return this.commentaireId;
	}

	public void setCommentaireId(int commentaireId) {
		this.commentaireId = commentaireId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sportifs_Login_id", nullable = false)
	public Sportifs getSportifs() {
		return this.sportifs;
	}

	public void setSportifs(Sportifs sportifs) {
		this.sportifs = sportifs;
	}

	@Column(name = "Expediteur", length = 50)
	public String getExpediteur() {
		return this.expediteur;
	}

	public void setExpediteur(String expediteur) {
		this.expediteur = expediteur;
	}

	@Column(name = "Contenue", length = 500)
	public String getContenue() {
		return this.contenue;
	}

	public void setContenue(String contenue) {
		this.contenue = contenue;
	}

	@Column(name = "Note")
	public Integer getNote() {
		return this.note;
	}

	public void setNote(Integer note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_record", length = 10)
	public Date getDateRecord() {
		return this.dateRecord;
	}

	public void setDateRecord(Date dateRecord) {
		this.dateRecord = dateRecord;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commentaire")
	public Set<ActiviteRecord> getActiviteRecords() {
		return this.activiteRecords;
	}

	public void setActiviteRecords(Set<ActiviteRecord> activiteRecords) {
		this.activiteRecords = activiteRecords;
	}

}
