package fr.formation.inti.entities;
// Generated 10 sept. 2019 09:21:11 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name = "commentaire", catalog = "sportnat")
public class Commentaire implements java.io.Serializable {

	private int commentaireId;
	private String contenue;
	private Integer note;
	private Date dateRecord;
	private int activiteRecordActiviteId1;
	private int sportifsSportifsId1;

	public Commentaire() {
	}

	public Commentaire(int commentaireId, int activiteRecordActiviteId1, int sportifsSportifsId1) {
		this.commentaireId = commentaireId;
		this.activiteRecordActiviteId1 = activiteRecordActiviteId1;
		this.sportifsSportifsId1 = sportifsSportifsId1;
	}

	public Commentaire(int commentaireId, String contenue, Integer note, Date dateRecord, int activiteRecordActiviteId1,
			int sportifsSportifsId1) {
		this.commentaireId = commentaireId;
		this.contenue = contenue;
		this.note = note;
		this.dateRecord = dateRecord;
		this.activiteRecordActiviteId1 = activiteRecordActiviteId1;
		this.sportifsSportifsId1 = sportifsSportifsId1;
	}

	@Id

	@Column(name = "commentaire_id", unique = true, nullable = false)
	public int getCommentaireId() {
		return this.commentaireId;
	}

	public void setCommentaireId(int commentaireId) {
		this.commentaireId = commentaireId;
	}

	@Column(name = "contenue", length = 500)
	public String getContenue() {
		return this.contenue;
	}

	public void setContenue(String contenue) {
		this.contenue = contenue;
	}

	@Column(name = "note")
	public Integer getNote() {
		return this.note;
	}

	public void setNote(Integer note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_record", length = 10)
	public Date getDateRecord() {
		return this.dateRecord;
	}

	public void setDateRecord(Date dateRecord) {
		this.dateRecord = dateRecord;
	}

	@Column(name = "activite_record_Activite_id1", nullable = false)
	public int getActiviteRecordActiviteId1() {
		return this.activiteRecordActiviteId1;
	}

	public void setActiviteRecordActiviteId1(int activiteRecordActiviteId1) {
		this.activiteRecordActiviteId1 = activiteRecordActiviteId1;
	}

	@Column(name = "sportifs_sportifs_id1", nullable = false)
	public int getSportifsSportifsId1() {
		return this.sportifsSportifsId1;
	}

	public void setSportifsSportifsId1(int sportifsSportifsId1) {
		this.sportifsSportifsId1 = sportifsSportifsId1;
	}

}
