package fr.formation.inti.entities;
// Generated 9 sept. 2019 11:09:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name = "commentaire", catalog = "sportnat")
public class Commentaire implements java.io.Serializable {

	private int commentaireId;
	private String contenue;
	private Integer note;
	private Date dateRecord;
	private int activiteRecordActiviteId;
	private int sportifsSportifsId;

	public Commentaire() {
	}

	public Commentaire(int commentaireId, int activiteRecordActiviteId, int sportifsSportifsId) {
		this.commentaireId = commentaireId;
		this.activiteRecordActiviteId = activiteRecordActiviteId;
		this.sportifsSportifsId = sportifsSportifsId;
	}

	public Commentaire(int commentaireId, String contenue, Integer note, Date dateRecord, int activiteRecordActiviteId,
			int sportifsSportifsId) {
		this.commentaireId = commentaireId;
		this.contenue = contenue;
		this.note = note;
		this.dateRecord = dateRecord;
		this.activiteRecordActiviteId = activiteRecordActiviteId;
		this.sportifsSportifsId = sportifsSportifsId;
	}

	@Id

	@Column(name = "commentaire_id", unique = true, nullable = false)
	public int getCommentaireId() {
		return this.commentaireId;
	}

	public void setCommentaireId(int commentaireId) {
		this.commentaireId = commentaireId;
	}

	@Column(name = "contenue", length = 500)
	public String getContenue() {
		return this.contenue;
	}

	public void setContenue(String contenue) {
		this.contenue = contenue;
	}

	@Column(name = "note")
	public Integer getNote() {
		return this.note;
	}

	public void setNote(Integer note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_record", length = 10)
	public Date getDateRecord() {
		return this.dateRecord;
	}

	public void setDateRecord(Date dateRecord) {
		this.dateRecord = dateRecord;
	}

	@Column(name = "activite_record_Activite_id", nullable = false)
	public int getActiviteRecordActiviteId() {
		return this.activiteRecordActiviteId;
	}

	public void setActiviteRecordActiviteId(int activiteRecordActiviteId) {
		this.activiteRecordActiviteId = activiteRecordActiviteId;
	}

	@Column(name = "sportifs_sportifs_id", nullable = false)
	public int getSportifsSportifsId() {
		return this.sportifsSportifsId;
	}

	public void setSportifsSportifsId(int sportifsSportifsId) {
		this.sportifsSportifsId = sportifsSportifsId;
	}

}
