package fr.formation.inti.entities;
// Generated 6 sept. 2019 09:54:53 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginId generated by hbm2java
 */
@Embeddable
public class LoginId implements java.io.Serializable {

	private int loginId;
	private int sportifsLoginId;

	public LoginId() {
	}

	public LoginId(int loginId, int sportifsLoginId) {
		this.loginId = loginId;
		this.sportifsLoginId = sportifsLoginId;
	}

	@Column(name = "Login_id", nullable = false)
	public int getLoginId() {
		return this.loginId;
	}

	public void setLoginId(int loginId) {
		this.loginId = loginId;
	}

	@Column(name = "sportifs_Login_id", nullable = false)
	public int getSportifsLoginId() {
		return this.sportifsLoginId;
	}

	public void setSportifsLoginId(int sportifsLoginId) {
		this.sportifsLoginId = sportifsLoginId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginId))
			return false;
		LoginId castOther = (LoginId) other;

		return (this.getLoginId() == castOther.getLoginId())
				&& (this.getSportifsLoginId() == castOther.getSportifsLoginId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLoginId();
		result = 37 * result + this.getSportifsLoginId();
		return result;
	}

}
