package fr.formation.inti.entities;
// Generated 5 sept. 2019 16:09:45 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "sportnat")
public class Login implements java.io.Serializable {

	private LoginId id;
	private Sportifs sportifs;
	private String email;
	private String mdp;

	public Login() {
	}

	public Login(LoginId id, Sportifs sportifs) {
		this.id = id;
		this.sportifs = sportifs;
	}

	public Login(LoginId id, Sportifs sportifs, String email, String mdp) {
		this.id = id;
		this.sportifs = sportifs;
		this.email = email;
		this.mdp = mdp;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "loginId", column = @Column(name = "Login_id", nullable = false)),
			@AttributeOverride(name = "sportifsLoginId", column = @Column(name = "sportifs_Login_id", nullable = false)) })
	public LoginId getId() {
		return this.id;
	}

	public void setId(LoginId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sportifs_Login_id", nullable = false, insertable = false, updatable = false)
	public Sportifs getSportifs() {
		return this.sportifs;
	}

	public void setSportifs(Sportifs sportifs) {
		this.sportifs = sportifs;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Mdp", length = 50)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

}
