package fr.formation.inti.entities;
// Generated 9 sept. 2019 11:09:20 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sportifs generated by hbm2java
 */
@Entity
@Table(name = "sportifs", catalog = "sportnat")
public class Sportifs implements java.io.Serializable {

	private int sportifsId;
	private String nom;
	private String prenom;
	private Integer age;
	private String titre;

	public Sportifs() {
	}

	public Sportifs(int sportifsId) {
		this.sportifsId = sportifsId;
	}

	public Sportifs(int sportifsId, String nom, String prenom, Integer age, String titre) {
		this.sportifsId = sportifsId;
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
		this.titre = titre;
	}

	@Id

	@Column(name = "sportifs_id", unique = true, nullable = false)
	public int getSportifsId() {
		return this.sportifsId;
	}

	public void setSportifsId(int sportifsId) {
		this.sportifsId = sportifsId;
	}

	

	

	@Column(name = "Nom", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "Titre", length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

}
