package fr.formation.inti.entities;
// Generated 10 sept. 2019 09:21:11 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sportifs generated by hbm2java
 */
@Entity
@Table(name = "sportifs", catalog = "sportnat")
public class Sportifs implements java.io.Serializable {

	private Integer sportifsId;
	private String nom;
	private String prenom;
	private Integer age;
	private String titre;
	private String tel;
//	private long appUserUserId;

	public Sportifs() {
	}

//	public Sportifs(long appUserUserId) {
//		this.appUserUserId = appUserUserId;
//	}

	public Sportifs(String nom, String prenom, Integer age, String titre, long appUserUserId) {
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
		this.titre = titre;
//		this.appUserUserId = appUserUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sportifs_id", unique = true, nullable = false)
	public Integer getSportifsId() {
		return this.sportifsId;
	}

	public void setSportifsId(Integer sportifsId) {
		this.sportifsId = sportifsId;
	}

	@Column(name = "Nom", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "Titre", length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

//	@Column(name = "app_user_USER_ID", nullable = false)
//	public long getAppUserUserId() {
//		return this.appUserUserId;
//	}
//
//	public void setAppUserUserId(long appUserUserId) {
//		this.appUserUserId = appUserUserId;
//	}

}
