package fr.formation.inti.entities;
// Generated 5 sept. 2019 16:09:45 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sportifs generated by hbm2java
 */
@Entity
@Table(name = "sportifs", catalog = "sportnat")
public class Sportifs implements java.io.Serializable {

	private Integer loginId;
	private String email;
	private String mdp;
	private String nom;
	private String prenom;
	private Integer age;
	private String titre;
	private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);
	private Set<Login> logins = new HashSet<Login>(0);
	private Set<ActiviteRecord> activiteRecords = new HashSet<ActiviteRecord>(0);

	public Sportifs() {
	}

	public Sportifs(String email, String mdp, String nom, String prenom, Integer age, String titre,
			Set<Commentaire> commentaires, Set<Login> logins, Set<ActiviteRecord> activiteRecords) {
		this.email = email;
		this.mdp = mdp;
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
		this.titre = titre;
		this.commentaires = commentaires;
		this.logins = logins;
		this.activiteRecords = activiteRecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Login_id", unique = true, nullable = false)
	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Mdp", length = 50)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column(name = "Nom", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "Titre", length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sportifs")
	public Set<Commentaire> getCommentaires() {
		return this.commentaires;
	}

	public void setCommentaires(Set<Commentaire> commentaires) {
		this.commentaires = commentaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sportifs")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "activite_record_has_sportifs", catalog = "sportnat", joinColumns = {
			@JoinColumn(name = "sportifs_Login_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "activite_record_Activite_id", nullable = false, updatable = false) })
	public Set<ActiviteRecord> getActiviteRecords() {
		return this.activiteRecords;
	}

	public void setActiviteRecords(Set<ActiviteRecord> activiteRecords) {
		this.activiteRecords = activiteRecords;
	}

}
