package fr.formation.inti.entities;
// Generated 10 sept. 2019 09:21:11 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "sportnat", uniqueConstraints = @UniqueConstraint(columnNames = { "USER_ID",
		"ROLE_ID" }))
public class UserRole implements java.io.Serializable {

	private long id;
	private long userId;
	private long roleId;

	public UserRole() {
	}

	public UserRole(long id, long userId, long roleId) {
		this.id = id;
		this.userId = userId;
		this.roleId = roleId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "USER_ID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

}
